# Generated by Django 4.2.30 on 2026-09-23 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_app_like",
                    models.BooleanField(default=True, verbose_name="Likes (in-app)"),
                ),
                (
                    "in_app_comment",
                    models.BooleanField(
                        default=True, verbose_name="Comments and replies (in-app)"
                    ),
                ),
                (
                    "in_app_follow",
                    models.BooleanField(
                        default=True, verbose_name="New followers (in-app)"
                    ),
                ),
                (
                    "in_app_mention",
                    models.BooleanField(default=True, verbose_name="Mentions (in-app)"),
                ),
                (
                    "in_app_post",
                    models.BooleanField(
                        default=True,
                        verbose_name="New posts from people you follow (in-app)",
                    ),
                ),
                (
                    "email_like",
                    models.BooleanField(default=False, verbose_name="Likes (email)"),
                ),
                (
                    "email_comment",
                    models.BooleanField(
                        default=True, verbose_name="Comments and replies (email)"
                    ),
                ),
                (
                    "email_follow",
                    models.BooleanField(
                        default=True, verbose_name="New followers (email)"
                    ),
                ),
                (
                    "email_mention",
                    models.BooleanField(default=True, verbose_name="Mentions (email)"),
                ),
                (
                    "email_post",
                    models.BooleanField(
                        default=False,
                        verbose_name="New posts from people you follow (email)",
                    ),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("none", "Never (send each email immediately)"),
                            ("daily", "Daily digest"),
                            ("weekly", "Weekly digest"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification preference",
                "verbose_name_plural": "Notification preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("follow", "Follow"),
                            ("mention", "Mention"),
                            ("post", "New Post"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["is_read", "created_at"],
                        name="notificatio_is_read_3a06ff_idx",
                    ),
                ],
            },
        ),
    ]
